Feature/members
RailonA/members_only pull request #1
Opened 2021-03-18 19:53 UTC by RailonA

A rails Members Only project
> This is part of the Forms Project in The Odin Project’s Ruby on Rails Curriculum. Find it at https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication

Set up a User account where you will be able to post only when logged in.

2021-03-19 00:21 UTC, enaburekhan requested changes
# Status: Changes required:full_moon:
**Hi team!
Great job so far on this project:clap::clap:.**

**Major highlights**

- The readme and PR is very descriptive and hence, professional
- The UI is awesome.
- The codebase is clean and codes are clearly written,

However, we still need to make a few changes to get this project approved:muscle:.

**To improve**

- [x] make the develop the default branch. Instead of the master which will always be the default if not changed.

- [ ] PostsController

- it uses `before_action` to restrict access to the `:new` and `:create` methods (uses ApplicationController helper method) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/before_action_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))

`before_action :signed_in_only!, only: [:new, :create]`
```ruby
def signed_in_only!
  # current_user in ApplicationController must be defined as helper method to make it work
  redirect_to  new_user_session_path unless current_user

  ## alternative solution:
  # if signed_in? is defined in ApplicationController (see stretch requirements)
  redirect_to new_user_session_path unless signed_in?
end
``` 
You can achieve this by using a helper. And then use the before action to restrict access to only `new` and `create` inside the posts controller.
 

- new

1. it initializes an empty post `@post = Post.new` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_new_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))

- [ ] As already highlighted below. There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it. Move all the logic highlighted below in the PR to a helper. Check this [article](http://codefol.io/posts/Where-Do-I-Put-My-Code/) and this [article](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers) on how to use a rails helper. See [screen-shot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from pathwright

- [ ] Delete edit and show action in posts_controller.rb. Since they were not used and hence, not required.

Make the required changes and when you are ready, request another review.
Have any question/comment? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond
Happy hacking:blush:
Eric Enaburekhan

2021-03-19 00:21 UTC, enaburekhan commented on README.md
> +- Then look at all User to make sure that information used to greate the user account was pushed successfully to the database.
Kindly correct spelling error `greate` to `create`

2021-03-19 00:21 UTC, enaburekhan commented on app/views/layouts/application.html.erb
> +	  <% end %>
There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it. Kindly move them to a helper

2021-03-19 00:21 UTC, enaburekhan commented on app/views/posts/index.html.erb
> +          <%= render "feed" %>
Move this logic to a helper.

2021-03-19 00:21 UTC, enaburekhan commented on app/views/shared/_navbar.html.erb
> +             <% end %>
Move this logic to a helper.

2021-03-20 08:31 UTC, enaburekhan requested changes
# Status: Changes required:full_moon:
**Hi team!
Great job so far. Thank you for implementing some of the changes earlier requested:clap::clap:. We are almost there now. The readme is very descriptive and the codebase is clean, easy to read and understand.
However, we just need to make a few changes to get this project approved:muscle:.**

**To improve**
- [ ]  Check my comments below on the view section. As earlier highlighted. There should be absolutely NO logic in views. Views are only for displaying information that became available to it from its corresponding controller not generating it. We still have logics in _feed.html.erb under posts, and _navbar.html.erb. Kindly move them to a helper. 

- [ ] Make the develop or development branch the default branch and not the master branch ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/git_flow_requirement.png) from Pathwright)

Make the above-required changes and when you are ready, request another review.
Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

2021-03-20 08:31 UTC, enaburekhan commented on app/views/posts/_feed.html.erb
> +                    <strong><%= post.user.name %></strong><br/>
Move this logic to a helper. As highlighted in the last review. There should be absolutely no logic in view.

2021-03-20 08:31 UTC, enaburekhan commented on app/views/posts/_feed.html.erb
> +                  <%end%>
Move the logic to a helper.

2021-03-20 08:31 UTC, enaburekhan commented on app/views/shared/_navbar.html.erb
> +             <% end %>
:point_up:

2021-03-22 17:00 UTC, MahmoudBakr23 requested changes
## **Changes Required 🛑♻**

<hr>

Hello there :)
Great job you've done on this app and on the requested changes. You've refactored all the logic from the views, and thanks for the extra work you made on editing and deleting posts. However, there is still one small change in order to get the approval 👍 

- [x] When I create posts with a user, then login with another user, the posts' author becomes the new user, not the user that actually created those posts. Kindly fix this issue.

<hr>

Good luck and happy coding 😊👨‍💻💻

2021-03-22 17:01 UTC, MahmoudBakr23 requested changes
## **Changes Required 🛑♻**

<hr>

Hello there :)
Great job you've done on this app and on the requested changes. You've refactored all the logic from the views, and thanks for the extra work you made on editing and deleting posts. However, there is still one small change in order to get the approval 👍 

- [ ] When I create posts with a user, then login with another user, the posts' author becomes the new user, not the user that actually created those posts. Kindly fix this issue.

<hr>

Good luck and happy coding 😊👨‍💻💻

2021-03-23 03:24 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Ismael Ngalula Antonio & Railon Acosta** 
Good job with the improvements for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
There are a couple of details to improve before you can go ahead:

- [ ] Don't overuse rubocop disable
- [ ] Fix rubocop offenses
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

2021-03-23 14:16 UTC, jubaan approved these changes

2021-03-23 14:57 UTC, merged